### ISSUE TITLE
 Abandoned contact form 7 Bug

### ISSUE THREAD

**Issue by rituzwt** [zealousweb/abandoned-contact-form-7#1]
Testing with latest Wordpress version 6.01 and Contact form 7 latest Version 5.6.1
- Admin panel side - The User IP is not displaying - https://prnt.sc/lcGBZ4DFpcDJ
- All the entries  of first IP address disappears when  submitting the form with another IP address. - https://prnt.sc/WhMeaRgckxHt

**Comment by rszwt** [comment]
Hello @rituzwt 

- Admin panel side - The User IP is not displaying - https://prnt.sc/lcGBZ4DFpcDJ
  - Please check this functionality with live server not local server.
- All the entries of first IP address disappears when submitting the form with another IP address. - https://prnt.sc/WhMeaRgckxHt
  - It's functionality not a bug. when user submitted the data successfully then not need to store data in entries.
